name: Deploy Backend

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/deploy-backend.yml"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t reggae-app ./backend

      - name: Tag image & Push Docker image to Amazon ECR
        run: |
          IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY }}:latest"
          docker tag reggae-app:latest $IMAGE_URI
          docker push $IMAGE_URI

      - name: Deploy on Backend EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_BACKEND_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY }}:latest"
            docker pull $IMAGE_URI
            docker stop backend || true
            docker rm backend || true
            docker run -d --name backend -p 80:8080 $IMAGE_URI

#      - name: Deploy on Backend EC2
#        run: |
#          IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY }}:latest"
#
#          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
#          chmod 600 private_key.pem
#
#          ssh -o StrictHostKeyChecking=no -i private_key.pem \
#          ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_BACKEND_HOST }} << EOF
#            docker pull $IMAGE_URI
#            docker stop backend || true
#            docker rm backend || true
#            docker run -d --name backend -p 80:8080 $IMAGE_URI
#          EOF
